[project]
name = "pynetwizard"
version = "0.2.0"
description = "Graphical network device configurator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "netmiko>=4.6.0",
    "pyside6>=6.9.3",
    "python-nmap>=0.7.1",
]
